sudo: false

language: node_js
node_js:
  - "5"

cache:
  directories:
  - node_modules
  - tests/elm-stuff
  - elm-stuff

install:
  - npm install -g elm
  - npm install
  - elm-package install -y

script:
  - make dist
  - make test
