sudo: false

language: node_js
node_js:
  - "5"

cache:
  directories:
  - node_modules
  - tests/elm-stuff
  - elm-stuff

install:
  - npm install -g elm
  - npm install
  - elm-package install -y
  - cd tests && elm-package install -y && cd ..

script:
  - make build
  - make test
